---
#title: ''
#author: "Maryam Seifeldin"
#date: "4/16/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(dplyr)
library(ggplot2)
library(ltm)
library(car)
library(gmodels)

choice_data <- read.csv("ExampleData_choice.csv", header=TRUE)
numeric_data <- read.csv("ExampleData_numeric.csv", header=TRUE)
numeric_data <- subset(numeric_data, Consent==1)
choice_data <- subset(choice_data, Consent=="Yes")
choice_data <- choice_data[, -c(1:17)]
numeric_data <- numeric_data[, -c(1:17)]
numeric_data$SDO1R <- recode(numeric_data$SDO1,"1=7; 2=6; 3=5; 4=4; 5=3; 6=2; 7=1; else=NA")
numeric_data$SDO2R <- recode(numeric_data$SDO2,"1=7; 2=6; 3=5; 4=4; 5=3; 6=2; 7=1; else=NA")
numeric_data$SDO5R <- recode(numeric_data$SDO5,"1=7; 2=6; 3=5; 4=4; 5=3; 6=2; 7=1; else=NA")
numeric_data$SDO6R <- recode(numeric_data$SDO6,"1=7; 2=6; 3=5; 4=4; 5=3; 6=2; 7=1; else=NA")
SDO <- data.frame(numeric_data$SDO1R, numeric_data$SDO2R, 
                  numeric_data$SDO3, numeric_data$SDO4, 
                  numeric_data$SDO5R, numeric_data$SDO6R,
                  numeric_data$SDO7, numeric_data$SDO8)
SDO <- mutate_all(SDO, function(x) as.numeric(as.character(x)))
SDO$SDO_mean_scores <- rowMeans(SDO, na.rm = TRUE)
```
For our analyses, we need: the demographics Gender & Age, the IVs Condition & Political Party, and the DV SDO
```{r, eval = TRUE} 
analysis_data <- data.frame(choice_data$GEND, numeric_data$AGE, choice_data$condition, choice_data$PPP1, SDO$SDO_mean_scores)
```
Next, because the method we used to make this dataframe results in some rather cumbersome column names to deal with, we'll give all the columns in this new dataframe easy intuitive names like this:
```{r, eval = TRUE} 
names(analysis_data) <- c("Gender", "Age", "Condition","PoliticalParty", "SocialDominance")
```

