---
# title: "Tutorial"
# author: "Maryam Seifeldin"
# date: "11/4/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(dplyr)
library(ggplot2)
library(ltm)
library(car)
library(gmodels)

choice_data <- read.csv("ExampleData_choice.csv", header=TRUE)
numeric_data <- read.csv("ExampleData_numeric.csv", header=TRUE)
numeric_data <- subset(numeric_data, Consent==1)
choice_data <- subset(choice_data, Consent=="Yes")
choice_data <- choice_data[, -c(1:17)]
numeric_data <- numeric_data[, -c(1:17)]
numeric_data$SDO1R <- recode(numeric_data$SDO1,"1=7; 2=6; 3=5; 4=4; 5=3; 6=2; 7=1; else=NA")
numeric_data$SDO2R <- recode(numeric_data$SDO2,"1=7; 2=6; 3=5; 4=4; 5=3; 6=2; 7=1; else=NA")
numeric_data$SDO5R <- recode(numeric_data$SDO5,"1=7; 2=6; 3=5; 4=4; 5=3; 6=2; 7=1; else=NA")
numeric_data$SDO6R <- recode(numeric_data$SDO6,"1=7; 2=6; 3=5; 4=4; 5=3; 6=2; 7=1; else=NA")
SDO <- data.frame(numeric_data$SDO1R, numeric_data$SDO2R, 
                  numeric_data$SDO3, numeric_data$SDO4, 
                  numeric_data$SDO5R, numeric_data$SDO6R,
                  numeric_data$SDO7, numeric_data$SDO8)
SDO <- mutate_all(SDO, function(x) as.numeric(as.character(x)))
SDO$SDO_mean_scores <- rowMeans(SDO, na.rm = TRUE)
analysis_data <- data.frame(choice_data$GEND, numeric_data$AGE, choice_data$condition, choice_data$PPP1, SDO$SDO_mean_scores)
names(analysis_data) <- c("Gender", "Age", "Condition","PoliticalParty", "SocialDominance")
analysis_data$Age <- as.numeric(as.character(analysis_data$Age))
```
Here we analyze the correlation between age and social dominance orientation:
```{r, eval = TRUE} 
age_x_sdo <- cor.test(analysis_data$Age, analysis_data$SocialDominance, 
                method = "pearson")
age_x_sdo
```
You'll need the p-value and the r-value (cor) to report a correlation properly.
